# Generated by Django 5.0.7 on 2024-07-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrefreshtoken_delete_emailcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRefreshToken',
        ),
    ]
