# Generated by Django 5.0.7 on 2024-07-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_push_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='interval',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Alarm_Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to='notifications.alarm')),
            ],
        ),
        migrations.CreateModel(
            name='Timer_Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='notifications.timer')),
            ],
        ),
    ]
