# Generated by Django 5.0.7 on 2024-07-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_timer_interval_alarm_push_timer_push'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alarm_Push',
            new_name='AlarmPush',
        ),
        migrations.RenameModel(
            old_name='Timer_Push',
            new_name='TimerPush',
        ),
    ]
