# Generated by Django 5.0.7 on 2024-07-31 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_alarm_push_alarmpush_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alarmpush',
            name='alarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to='notifications.alarm'),
        ),
        migrations.AlterField(
            model_name='alarmpush',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timerpush',
            name='timer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='notifications.timer'),
        ),
    ]
